### ISSUE TITLE
fails to compile with GHC 7.8/base-4.7

### ISSUE THREAD

**Issue by hvr** [noraesae/line#2]
Welcome to Hackage!

The Hackage matrix builder noticed this; if you don't want to support GHC 7.8/base-4.7, just change the lower on bound on `base` to say `base >= 4.8`

If you have any questions about Hackage, please let me know!

```
Configuring component lib from line-1.0.0.1
Warning: The package has a version range for a dependency on an internal library: line >=1.0.0.1 && <1.1. This version range has no semantic meaning and can be removed.
Preprocessing library line-1.0.0.1...
[1 of 7] Compiling Line.Messaging.Common.Types ( src/Line/Messaging/Common/Types.hs, /tmp/matrix-worker/1480240769/dist-newstyle/build/x86_64-linux/ghc-7.8.4/line-1.0.0.1/build/Line/Messaging/Common/Types.o )
[2 of 7] Compiling Line.Messaging.API.Types ( src/Line/Messaging/API/Types.hs, /tmp/matrix-worker/1480240769/dist-newstyle/build/x86_64-linux/ghc-7.8.4/line-1.0.0.1/build/Line/Messaging/API/Types.o )

src/Line/Messaging/API/Types.hs:105:31:
    Not in scope: ‘<$>’
    Perhaps you meant ‘<|>’ (imported from Control.Applicative)

src/Line/Messaging/API/Types.hs:177:35:
    Not in scope: ‘<$>’
    Perhaps you meant ‘<|>’ (imported from Control.Applicative)

src/Line/Messaging/API/Types.hs:178:35:
    Not in scope: ‘<*>’
    Perhaps you meant ‘<|>’ (imported from Control.Applicative)

src/Line/Messaging/API/Types.hs:179:35:
    Not in scope: ‘<*>’
    Perhaps you meant ‘<|>’ (imported from Control.Applicative)

src/Line/Messaging/API/Types.hs:180:35:
    Not in scope: ‘<*>’
    Perhaps you meant ‘<|>’ (imported from Control.Applicative)

src/Line/Messaging/API/Types.hs:206:34:
    Not in scope: ‘<$>’
    Perhaps you meant ‘<|>’ (imported from Control.Applicative)

src/Line/Messaging/API/Types.hs:207:34:
    Not in scope: ‘<*>’
    Perhaps you meant ‘<|>’ (imported from Control.Applicative)

src/Line/Messaging/API/Types.hs:442:34:
    Not in scope: ‘<$>’
    Perhaps you meant ‘<|>’ (imported from Control.Applicative)

src/Line/Messaging/API/Types.hs:443:34:
    Not in scope: ‘<*>’
    Perhaps you meant ‘<|>’ (imported from Control.Applicative)

src/Line/Messaging/API/Types.hs:444:34:
    Not in scope: ‘<*>’
    Perhaps you meant ‘<|>’ (imported from Control.Applicative)

src/Line/Messaging/API/Types.hs:445:34:
    Not in scope: ‘<*>’
    Perhaps you meant ‘<|>’ (imported from Control.Applicative)

src/Line/Messaging/API/Types.hs:492:39:
    Not in scope: ‘<$>’
    Perhaps you meant ‘<|>’ (imported from Control.Applicative)

src/Line/Messaging/API/Types.hs:493:39:
    Not in scope: ‘<*>’
    Perhaps you meant ‘<|>’ (imported from Control.Applicative)

src/Line/Messaging/API/Types.hs:494:39:
    Not in scope: ‘<*>’
    Perhaps you meant ‘<|>’ (imported from Control.Applicative)
```

**Comment by noraesae** [comment]
Thanks for your help!

It looked easy to fix and actually tried to fix the issue, but unfortunately ghc 7.8 doesn't work in the latest macOS. I decided to just change the lower bound to base >= 7.8.
